#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODELS_DIR="${VOICE_IME_MIMO_ASR_MODELS_DIR:-$ROOT_DIR/vendor/models/mimo-asr}"
MODEL_PATH="${VOICE_IME_MIMO_ASR_MODEL_PATH:-$MODELS_DIR/MiMo-V2.5-ASR}"
TOKENIZER_PATH="${VOICE_IME_MIMO_ASR_TOKENIZER_PATH:-$MODELS_DIR/MiMo-Audio-Tokenizer}"
SRC_DIR="${VOICE_IME_MIMO_ASR_SOURCE:-$ROOT_DIR/vendor/MiMo-V2.5-ASR}"
VENV_PY="${VOICE_IME_MIMO_ASR_PYTHON:-$ROOT_DIR/.venv-mimo-asr/bin/python}"
MODEL_DEVICE_MAP="${VOICE_IME_MIMO_ASR_MODEL_DEVICE_MAP:-auto}"
MODEL_MAX_MEMORY="${VOICE_IME_MIMO_ASR_MODEL_MAX_MEMORY:-cuda:0=8GiB,cpu=64GiB}"
MODEL_OFFLOAD_FOLDER="${VOICE_IME_MIMO_ASR_MODEL_OFFLOAD_FOLDER:-$HOME/.local/share/ibus-voice-ime/mimo-offload}"
PYTORCH_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

if [[ ! -d "$MODEL_PATH" ]]; then
  echo "模型目录不存在：$MODEL_PATH，请先运行 scripts/setup-mimo-asr.sh" >&2
  exit 1
fi
if [[ ! -d "$TOKENIZER_PATH" ]]; then
  echo "Tokenizer 目录不存在：$TOKENIZER_PATH，请先运行 scripts/setup-mimo-asr.sh" >&2
  exit 1
fi
if [[ ! -d "$SRC_DIR" ]]; then
  echo "MiMo 源码目录不存在：$SRC_DIR，请先运行 scripts/setup-mimo-asr.sh" >&2
  exit 1
fi
if [[ ! -x "$VENV_PY" ]]; then
  echo "Python 虚拟环境不存在：$VENV_PY，请先运行 scripts/setup-mimo-asr.sh" >&2
  exit 1
fi

ENV_FILE="$HOME/.config/environment.d/ibus-voice-ime.conf"
mkdir -p "$(dirname "$ENV_FILE")" "$MODEL_OFFLOAD_FOLDER"
if [[ -f "$ENV_FILE" ]]; then
  TMP="$(mktemp)"
  grep -vE '^(VOICE_IME_ASR_BACKEND|VOICE_IME_QWEN_ASR|VOICE_IME_MIMO_ASR|VOICE_IME_MIMO_CLOUD_ASR|VOICE_IME_VOLC_BIGMODEL_ASR|VOICE_IME_SILICONFLOW|PYTORCH_CUDA_ALLOC_CONF)' "$ENV_FILE" > "$TMP" || true
  mv "$TMP" "$ENV_FILE"
fi
cat >> "$ENV_FILE" <<EOF_ENV
VOICE_IME_ASR_BACKEND=mimo-asr
VOICE_IME_QWEN_ASR=0
VOICE_IME_MIMO_ASR=1
VOICE_IME_MIMO_CLOUD_ASR=0
VOICE_IME_VOLC_BIGMODEL_ASR=0
VOICE_IME_SILICONFLOW_ASR=0
VOICE_IME_MIMO_ASR_MODEL_PATH=$MODEL_PATH
VOICE_IME_MIMO_ASR_TOKENIZER_PATH=$TOKENIZER_PATH
VOICE_IME_MIMO_ASR_SOURCE=$SRC_DIR
VOICE_IME_MIMO_ASR_PYTHON=$VENV_PY
VOICE_IME_MIMO_ASR_HOST=127.0.0.1
VOICE_IME_MIMO_ASR_PORT=18082
VOICE_IME_MIMO_ASR_LANGUAGE=auto
VOICE_IME_MIMO_ASR_DEVICE=cuda
VOICE_IME_MIMO_ASR_START_TIMEOUT=300
VOICE_IME_MIMO_ASR_TIMEOUT=300
VOICE_IME_MIMO_ASR_MODEL_DEVICE_MAP=$MODEL_DEVICE_MAP
VOICE_IME_MIMO_ASR_MODEL_MAX_MEMORY=$MODEL_MAX_MEMORY
VOICE_IME_MIMO_ASR_MODEL_OFFLOAD_FOLDER=$MODEL_OFFLOAD_FOLDER
PYTORCH_CUDA_ALLOC_CONF=$PYTORCH_ALLOC_CONF
EOF_ENV
systemctl --user set-environment \
  VOICE_IME_ASR_BACKEND=mimo-asr \
  VOICE_IME_QWEN_ASR=0 \
  VOICE_IME_MIMO_ASR=1 \
  VOICE_IME_MIMO_CLOUD_ASR=0 \
  VOICE_IME_VOLC_BIGMODEL_ASR=0 \
  VOICE_IME_SILICONFLOW_ASR=0 \
  "VOICE_IME_MIMO_ASR_MODEL_PATH=$MODEL_PATH" \
  "VOICE_IME_MIMO_ASR_TOKENIZER_PATH=$TOKENIZER_PATH" \
  "VOICE_IME_MIMO_ASR_SOURCE=$SRC_DIR" \
  "VOICE_IME_MIMO_ASR_PYTHON=$VENV_PY" \
  VOICE_IME_MIMO_ASR_HOST=127.0.0.1 \
  VOICE_IME_MIMO_ASR_PORT=18082 \
  VOICE_IME_MIMO_ASR_LANGUAGE=auto \
  VOICE_IME_MIMO_ASR_DEVICE=cuda \
  VOICE_IME_MIMO_ASR_START_TIMEOUT=300 \
  VOICE_IME_MIMO_ASR_TIMEOUT=300 \
  "VOICE_IME_MIMO_ASR_MODEL_DEVICE_MAP=$MODEL_DEVICE_MAP" \
  "VOICE_IME_MIMO_ASR_MODEL_MAX_MEMORY=$MODEL_MAX_MEMORY" \
  "VOICE_IME_MIMO_ASR_MODEL_OFFLOAD_FOLDER=$MODEL_OFFLOAD_FOLDER" \
  "PYTORCH_CUDA_ALLOC_CONF=$PYTORCH_ALLOC_CONF" 2>/dev/null || true
pkill -f 'python.*[m]imo_asr_server\.py' 2>/dev/null || true
pkill -f 'python.*[q]wen_asr_server\.py' 2>/dev/null || true
COMPONENT_DIR="$HOME/.local/share/ibus/component"
IBUS_COMPONENT_PATH_VALUE="$COMPONENT_DIR:/usr/share/ibus/component"
IBUS_COMPONENT_PATH="$IBUS_COMPONENT_PATH_VALUE" \
LD_LIBRARY_PATH="$ROOT_DIR/vendor/rime/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
VOICE_IME_RIME_LIBRARY="$ROOT_DIR/vendor/rime/lib/librime.so.1" \
VOICE_IME_RIME_SHARED_DATA_DIR="$ROOT_DIR/vendor/rime/share/rime-data" \
VOICE_IME_RIME_STAGING_DIR="$ROOT_DIR/vendor/rime/build" \
VOICE_IME_RIME_USER_DATA_DIR="$HOME/.local/share/ibus-voice-ime/rime-user" \
VOICE_IME_ASR_BACKEND=mimo-asr \
VOICE_IME_QWEN_ASR=0 \
VOICE_IME_MIMO_ASR=1 \
VOICE_IME_MIMO_CLOUD_ASR=0 \
VOICE_IME_VOLC_BIGMODEL_ASR=0 \
VOICE_IME_SILICONFLOW_ASR=0 \
VOICE_IME_MIMO_ASR_MODEL_PATH="$MODEL_PATH" \
VOICE_IME_MIMO_ASR_TOKENIZER_PATH="$TOKENIZER_PATH" \
VOICE_IME_MIMO_ASR_SOURCE="$SRC_DIR" \
VOICE_IME_MIMO_ASR_PYTHON="$VENV_PY" \
VOICE_IME_MIMO_ASR_HOST=127.0.0.1 \
VOICE_IME_MIMO_ASR_PORT=18082 \
VOICE_IME_MIMO_ASR_LANGUAGE=auto \
VOICE_IME_MIMO_ASR_DEVICE=cuda \
VOICE_IME_MIMO_ASR_START_TIMEOUT=300 \
VOICE_IME_MIMO_ASR_TIMEOUT=300 \
VOICE_IME_MIMO_ASR_MODEL_DEVICE_MAP="$MODEL_DEVICE_MAP" \
VOICE_IME_MIMO_ASR_MODEL_MAX_MEMORY="$MODEL_MAX_MEMORY" \
VOICE_IME_MIMO_ASR_MODEL_OFFLOAD_FOLDER="$MODEL_OFFLOAD_FOLDER" \
PYTORCH_CUDA_ALLOC_CONF="$PYTORCH_ALLOC_CONF" \
VOICE_IME_AUTO_PUNCTUATION="${VOICE_IME_AUTO_PUNCTUATION:-0}" \
VOICE_IME_LLM_POSTPROCESS="${VOICE_IME_SWITCH_LLM_POSTPROCESS:-0}" \
VOICE_IME_LLM_INTERNAL="${VOICE_IME_SWITCH_LLM_INTERNAL:-0}" \
VOICE_IME_LLM_TRUST_OUTPUT="${VOICE_IME_SWITCH_LLM_TRUST_OUTPUT:-1}" \
VOICE_IME_LLM_RERANK="${VOICE_IME_SWITCH_LLM_RERANK:-0}" \
VOICE_IME_LLM_CANDIDATES="${VOICE_IME_SWITCH_LLM_CANDIDATES:-1}" \
VOICE_IME_LLM_BASE_URL="${VOICE_IME_SWITCH_LLM_BASE_URL:-http://127.0.0.1:18080/v1}" \
VOICE_IME_LLM_API_KEY="${VOICE_IME_SWITCH_LLM_API_KEY:-local}" \
VOICE_IME_LLM_MODEL="${VOICE_IME_SWITCH_LLM_MODEL:-qwen3.5-0.8b}" \
VOICE_IME_LLM_LOG="${VOICE_IME_LLM_LOG:-$HOME/.local/share/ibus-voice-ime/llm.jsonl}" \
"$ROOT_DIR/scripts/ibus-restart.sh" >/dev/null || true
sleep 1
ibus engine voice-custom >/dev/null 2>&1 || true
echo "已切换到 MiMo-V2.5-ASR：$MODEL_PATH"
